#!/bin/bash

if [[ $UID == 1004 ]]; then

    echo "*******************************************************************************************************"
    echo "Now the real game begins! Let's see what you've got in your skillsets."
    echo "The author doesn't think that a simple ls command would cause security issues. prove that it's not true."
    echo "Good Luck on your new PATH!"
    echo "*******************************************************************************************************"

    read -p "Now give me a directory to list its contents (remember this is running with user3 so you only have user3's permissins) : " user_path

    ls -la $user_path
else
    echo "Sorry come again later."
fi
