#!/bin/bash

if [[ $UID == 1003 ]]; then

    echo "*******************************************************************************************************"
    echo "Hmmm, so you passed the level0 huh? that was not a challenge at all, but a feature :D"
    echo "OK the author has left this functinality for no reason and it doesn't seem to cause any problems :P"
    echo "*******************************************************************************************************"

    ./check_id.sh
    
else
    echo "Sorry come again later."
fi
