#!/bin/bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

if [[ $UID == 1005 ]]; then

    echo "*******************************************************************************************************"
    echo "hmmm it seems you've spoiled your PATH. here is your original PATH, fix it please."
    echo "I'll never let you again ruin my path 😡"
    echo ""
    echo $PATH
    echo ""
    echo "you don't look that bad at all bacuase you could come up until here, but from now, YOU SHALL NOT PASS !!!"
    echo "The author has implemented an authentication system. he believes that this is the worlds most secure authentication schema"
    echo "Let's see if you can bypass it."
    echo "*******************************************************************************************************"


    super_secret_password=$(cat /dev/urandom | head -c 16 | xxd -p)
    user4_password=$(cat /home/user4/cred4.txt | cut -d ':' -f2)

    read -p "Can you guess the password : " user_password
    echo ""

    if [[ $super_secret_password == $user_password ]]; then
        echo "Wow you guessed the super secret password. how wild! :P."
        echo "Here is your reward : ${user4_password}"
    else 
        echo "Oh I'm sorry that's not correct"
    fi

else
    echo "Oh what are you doing?!"
fi
