#!/bin/bash

$export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" 2>/dev/null

if [[ $UID == 1005 ]]; then

    echo "*******************************************************************************************************"
    echo "It seems there was a minor issue in previous level"
    echo "*******************************************************************************************************"


    super_secret_password=$(cat /dev/urandom | head -c 16 | xxd -p)
    user2_password=$(cat /home/user3/cred3.txt)

    read -s -p "Can you guess the password : " user_password

    if [[ $super_secret_password == $user_password ]]; then
        echo "Wow you guessed the super secret password. how wild! :P."
        echo "For your reward here is next user's password. good luck on your remaining path."
        echo $user2_password
    else 
        echo "Oh I'm sorry that's not correct"
    fi

else
    echo "Oh what are you doing?!"
fi