#!/bin/bash


export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

echo "Hmmm, you persisted for quite some time. but this game is over for you here !"
echo "why should someone think about designing authentication schema in BASH ?!"
echo "OK nevermind, After here it won't be easy, there is no way you can pass after here."

