#!/bin/bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" 2>/dev/null

if [[ $UID == 1005 ]]; then

    echo "*******************************************************************************************************"
    echo "It seems there was a minor issue in previous level. the author has patched the problem."
    echo "This level you should find next user's password. not by just being wild :D"
    echo "Good luck"
    echo "*******************************************************************************************************"


    user4_password=$(cat /home/user4/cred4.txt | cut -d ':' -f2)

    read -s -p "Can you guess the password : " user_password
    echo ""

    if [[ $user4_password == $user_password ]]; then
        echo "Nice try, but no more passwords for you!"
    else 
        echo "Oh I'm sorry that's not correct"
    fi

else
    echo "Oh what are you doing?!"
fi